import Link from "next/link";
import { requireAdmin } from "@/lib/auth/require-admin";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/format/date";

export default async function AdminPage() {
  await requireAdmin();
  const since = new Date(); since.setDate(since.getDate() - 29); since.setHours(0, 0, 0, 0);
  const [users, expenses, notifications, ai, categoryStats, expenseTrend, notificationTrend] = await Promise.all([
    prisma.user.count(), prisma.expense.count(), prisma.notification.count(),
    prisma.aiCategorization.groupBy({ by: ["status"], _count: { _all: true } }),
    prisma.category.findMany({ where: { type: "SYSTEM", userId: null }, select: { name: true, icon: true, _count: { select: { expenses: true } } }, orderBy: { expenses: { _count: "desc" } }, take: 6 }),
    prisma.expense.findMany({ where: { createdAt: { gte: since } }, select: { createdAt: true, amount: true, type: true } }),
    prisma.notification.findMany({ where: { createdAt: { gte: since } }, select: { createdAt: true, isRead: true } }),
  ]);
  const day = (date: Date) => date.toISOString().slice(0, 10);
  const makeTrend = <T extends { createdAt: Date },>(items: T[], value: (item: T) => number) => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - 6 + index); const key = day(date); return { label: formatDate(date, "id", { weekday: "short" }), value: items.filter((item) => day(item.createdAt) === key).reduce((sum, item) => sum + value(item), 0) }; });
  const expensePoints = makeTrend(expenseTrend, (item) => item.type === "EXPENSE" ? Number(item.amount) : 0);
  const notificationPoints = makeTrend(notificationTrend, () => 1);
  const maxExpense = Math.max(...expensePoints.map((point) => point.value), 1); const maxNotification = Math.max(...notificationPoints.map((point) => point.value), 1);
  const aiCount = (status: "PENDING" | "COMPLETED" | "FAILED") => ai.find((item) => item.status === status)?._count._all ?? 0;
  const links = [["Users", "/admin/users"], ["System categories", "/admin/categories"], ["Expenses", "/admin/expenses"], ["Notifications", "/admin/notifications"], ["AI categorizations", "/admin/ai-categorizations"]];
  return <main className="flex flex-1 flex-col gap-6 p-6"><div><h1 className="text-2xl font-bold tracking-tight">Admin analytics</h1><p className="text-sm text-muted-foreground">Platform activity for the last 30 days.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Users" value={users} /><Metric title="Transactions" value={expenses} /><Metric title="Notifications" value={notifications} /><Metric title="AI completed" value={aiCount("COMPLETED")} /></section><section className="grid gap-4 xl:grid-cols-2"><Chart title="Expense volume" subtitle="Expense amount created in the last 7 days" points={expensePoints} max={maxExpense} format={(value) => new Intl.NumberFormat("id-ID", { notation: "compact" }).format(value)} /><Chart title="Notifications" subtitle="Notifications created in the last 7 days" points={notificationPoints} max={maxNotification} format={(value) => String(value)} /></section><section className="grid gap-4 xl:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">System category usage</h2><div className="mt-4 space-y-3">{categoryStats.map((category) => <div key={category.name} className="flex justify-between text-sm"><span>{category.icon} {category.name}</span><span className="text-muted-foreground">{category._count.expenses} expenses</span></div>)}</div></div><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">AI categorization</h2><div className="mt-4 grid grid-cols-3 gap-3"><Metric title="Completed" value={aiCount("COMPLETED")} compact /><Metric title="Pending" value={aiCount("PENDING")} compact /><Metric title="Failed" value={aiCount("FAILED")} compact /></div></div></section><section className="flex flex-wrap gap-3">{links.map(([label, href]) => <Link key={href} href={href} className="rounded-lg border px-3 py-2 text-sm hover:bg-muted">Manage {label}</Link>)}</section></main>;
}
function Metric({ title, value, compact = false }: { title: string; value: number; compact?: boolean }) { return <div className={compact ? "rounded-lg bg-muted p-3" : "rounded-xl border bg-card p-5"}><p className="text-sm text-muted-foreground">{title}</p><p className={compact ? "mt-1 text-xl font-bold" : "mt-2 text-3xl font-bold"}>{value.toLocaleString("id-ID")}</p></div>; }
function Chart({ title, subtitle, points, max, format }: { title: string; subtitle: string; points: { label: string; value: number }[]; max: number; format: (value: number) => string }) { return <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">{title}</h2><p className="text-sm text-muted-foreground">{subtitle}</p><div className="mt-6 flex h-44 items-end gap-3">{points.map((point) => <div key={point.label} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] text-muted-foreground">{format(point.value)}</span><div className="w-full rounded-t bg-primary/80" style={{ height: `${Math.max((point.value / max) * 100, 3)}%` }} /><span className="text-xs text-muted-foreground">{point.label}</span></div>)}</div></div>; }
