"use client";
import { useState, useTransition } from "react";
import { createSystemCategory, deleteSystemCategory, updateSystemCategory } from "@/actions/admin";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
type Category = { id: string; name: string; description: string | null; icon: string | null; color: string | null; _count: { expenses: number; budgets: number } };
function FormFields({ category }: { category?: Category }) { return <><Input name="name" required defaultValue={category?.name} placeholder="Category name" /><Input name="icon" defaultValue={category?.icon ?? "🏷️"} placeholder="Icon" /><Input name="color" type="color" defaultValue={category?.color ?? "#64748B"} /><Input name="description" defaultValue={category?.description ?? ""} placeholder="Description" /></>; }
export function SystemCategoryManager({ categories }: { categories: Category[] }) { const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const [open, setOpen] = useState(false); async function create(data: FormData) { const result = await createSystemCategory(data); if (!result.success) setError(result.error ?? "Unable to create category."); else setOpen(false); } async function remove(id: string) { startTransition(async () => { const result = await deleteSystemCategory(id); if (!result.success) setError(result.error ?? "Unable to delete category."); }); } return <div className="space-y-4"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button>Add system category</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add system category</DialogTitle></DialogHeader><form action={create} className="space-y-3"><FormFields /><Button className="w-full">Create category</Button></form></DialogContent></Dialog>{error && <p className="text-sm text-destructive">{error}</p>}<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-sm"><thead className="border-b text-left text-muted-foreground"><tr><th className="p-3">Category</th><th className="p-3">Usage</th><th className="p-3">Actions</th></tr></thead><tbody>{categories.map((category) => <tr key={category.id} className="border-b last:border-0"><td className="p-3"><span className="mr-2">{category.icon}</span><b>{category.name}</b><p className="mt-1 text-xs text-muted-foreground">{category.description}</p></td><td className="p-3">{category._count.expenses} expenses · {category._count.budgets} budgets</td><td className="p-3"><Dialog><DialogTrigger asChild><Button size="sm" variant="outline">Edit</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit {category.name}</DialogTitle></DialogHeader><form action={async (data) => { await updateSystemCategory(category.id, data); }} className="space-y-3"><FormFields category={category} /><Button className="w-full">Save changes</Button></form></DialogContent></Dialog><Button size="sm" variant="ghost" disabled={pending} className="ml-2 text-destructive" onClick={() => remove(category.id)}>Delete</Button></td></tr>)}</tbody></table></div></div>; }
